# Generated by Django 4.2.7 on 2025-08-09 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid
import videos.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=50, null=True)),
                ('default_language', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_status', models.CharField(blank=True, max_length=20, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('duration', videos.fields.YouTubeDurationField(blank=True, max_length=20, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.channel')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['-published_at'],
            },
        ),
    ]
