# Generated by Django 4.2.7 on 2025-08-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_update_duration_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_watched',
        ),
    ]
