# Generated by Django 4.2.7 on 2025-12-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_channel_idx_ch_title_trgm_channel_idx_ch_desc_trgm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="is_available",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
