# Generated by Django 4.2.7 on 2025-09-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserYouTubeCredentials",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("encrypted_access_token", models.TextField(blank=True, null=True)),
                ("encrypted_refresh_token", models.TextField(blank=True, null=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("scopes", models.JSONField(default=list)),
                ("client_id", models.TextField(blank=True, null=True)),
                ("token_uri", models.URLField(default="https://oauth2.googleapis.com/token")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_youtube_credentials",
            },
        ),
    ]
