# Generated by Django 4.2.7 on 2025-09-26 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useryoutubecredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quota_used', models.IntegerField(default=0)),
                ('operations_count', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_daily_quotas',
                'indexes': [models.Index(fields=['user', 'date'], name='user_daily__user_id_70bd14_idx'), models.Index(fields=['date'], name='user_daily__date_26fdaf_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
