# Generated by Django 4.2.7 on 2025-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_enable_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userchannel',
            index=models.Index(fields=['user', 'is_active', 'channel'], name='idx_uc_user_active_channel'),
        ),
    ]
