# Generated by Django 4.2.7 on 2025-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_enable_pg_trgm_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservideo",
            name="is_not_interested",
            field=models.BooleanField(null=True, blank=True, default=None),
        ),
        migrations.AddField(
            model_name="uservideo",
            name="not_interested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="uservideo",
            index=models.Index(fields=["user", "is_not_interested"], name="user_not_interested_idx"),
        ),
    ]
