# Generated by Django 4.2.7 on 2025-11-07 15:25

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_not_interested_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWatchPreferences",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "auto_mark_watched_enabled",
                    models.BooleanField(default=True, help_text="Enable automatic marking of videos as watched"),
                ),
                (
                    "auto_mark_threshold",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Percentage threshold for auto-marking (0-100), uses DEFAULT_AUTO_MARK_THRESHOLD if null",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user watch preferences",
                "db_table": "user_watch_preferences",
            },
        ),
        migrations.AddField(
            model_name="uservideo",
            name="auto_marked_watched",
            field=models.BooleanField(default=False, help_text="True if automatically marked as watched via threshold"),
        ),
        migrations.AddField(
            model_name="uservideo",
            name="watch_progress_seconds",
            field=models.IntegerField(default=0, help_text="Current playback position in seconds"),
        ),
        migrations.AddIndex(
            model_name="uservideo",
            index=models.Index(fields=["user", "watch_progress_seconds"], name="user_watch_progress_idx"),
        ),
        migrations.AddField(
            model_name="userwatchpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
